### ISSUE TITLE
Ignore Gemfile.lock notifications

### ISSUE THREAD

**Issue by sarahjones** [appfolio/ladle#69]
If the only change is the Gemfile.lock, it would be nice if a notification wasn't issued.  Not a huge deal because in the email it is clear that it is only a Gemfile.lock, but it is clutter.

**Comment by dtognazzini** [comment]
Some folks may want to see changes in Gemfile.lock files. You can add ignore rules for areas you steward: https://github.com/appfolio/ladle#advanced
